name: spaceBattleTests

on:
  push:
    branches: [ "space_battle" ]

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET7
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x

      - name: Restore dependencies
        run: dotnet restore spaceBattleTests

      - name: Test Build
        run: dotnet build spaceBattleTests --no-restore /p:ContinuousIntegrationBuild=true

      - name: Run tests
        run: cd spaceBattleTests && dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura
        
